server:
  port: 23850
logging:
  file:
    path: ./logs
    name: ./logs/DataSyncTask.logs
  level:
    root: info


spring:
  datasource:
    dynamic:
      datasource:
        mysql:
          url: jdbc:mysql://116.62.188.148:3306/wx?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&AllowPublicKeyRetrieval=True
          username: root
          password: smf2020-
          driver-class-name: com.mysql.cj.jdbc.Driver
        sqlserver:
          url: jdbc:sqlserver://localhost:1433;DatabaseName=sync_data
          username: SA
          password: Root@1234
          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

mybatis-plus:
  global-config:
    enable-sql-runner: true
  mapper-locations: mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  type-aliases-package: com.liuhao.datasynctask.entity


wechat:
  #企业Id
  corpid: wwf63177e786ed5297
  #应用私钥
  corpsecret: flYV0dK_x0QMRsIwepCX-k37PgY-GOMvA7GXz269d0k
  #应用ID
  agentId: 1000003
  #获取token地址
  accessTokenUrl: https://qyapi.weixin.qq.com/cgi-bin/gettoken?corpid=CORPID&corpsecret=CORPSECRET
  #发送消息地址
  sendMessageUrl: https://qyapi.weixin.qq.com/cgi-bin/message/send?access_token=
  #获取用户id地址
  getUseridUrl: https://qyapi.weixin.qq.com/cgi-bin/user/getuserid?access_token=
  #获取访问用户身份
  getUserInfoUrl: https://qyapi.weixin.qq.com/cgi-bin/user/getuserinfo?access_token=ACCESS_TOKEN&code=CODE
  #获取企业的jsapi_ticket
  getJsapiTicketUrl: https://qyapi.weixin.qq.com/cgi-bin/get_jsapi_ticket?access_token=ACCESS_TOKEN
  #获取部门列表地址(企业微信api地址)
  getDepartmentListUrl: https://qyapi.weixin.qq.com/cgi-bin/department/list?access_token=ACCESS_TOKEN
  #获取部门成员详情地址(企业微信api地址)
  getUserListUrl: https://qyapi.weixin.qq.com/cgi-bin/user/list

debezium:
  database:
    - name: wx
      enabled: true
      serverId: 1
      host: 116.62.188.148
      port: 3306
      username: root
      password: smf2020-
      offset-path: offset.dat
      history-path: dbhistory.dat
      table:
        - wx.member_card_test

