server:
  port: 23851
logging:
  file:
    path: ./logs
    name: ./logs/DataSyncTask.logs
  level:
    root: error


spring:
  datasource:
    dynamic:
      datasource:
        mysql:
          url: jdbc:mysql://116.62.188.148:3306/wx?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&AllowPublicKeyRetrieval=True
          username: root
          password: smf2020-
          driver-class-name: com.mysql.jdbc.Driver
        sqlserver:
          url: jdbc:sqlserver://localhost:1433;DatabaseName=newideav1
          username: sa
          password: smf2020-
          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

debezium:
  database:
    - name: wx
      enabled: true
      serverId: 1
      host: 116.62.188.148
      port: 3306
      username: root
      password: smf2020-
      offset-path: offset.dat
      history-path: dbhistory.dat
      table:
        - wx.member_card


mybatis-plus:
  global-config:
    enable-sql-runner: true
  mapper-locations: mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  type-aliases-package: com.liuhao.datasynctask.entity



