server:
  port: 23849
logging:
  file:
    path: /Users/liuhao/Downloads/JavaProjects/DataSyncTask/logs
    name: /Users/liuhao/Downloads/JavaProjects/DataSyncTask/logs/DataSyncTask-1.logs
  level:
    root: info

#Debezium数据同步配置
timely:
  # 是否开启
  switch: true
  # 偏移量文件
  offset-file-name: E://lei/offsets.dat
  # 是否启动时清除偏移量文件
  offset-file-clean: true
  # 偏移量提交时间 单位ms
  offset-time: 1
  # 读取历史记录文件
  history-file-name: E://lei/dbhistory.dat
  # 读取的数据库信息
  offline:
    ip: 10.50.100.68
    port: 1433
    username: sa
    password: 8AL16x76NP3R
    # 保证每个数据库读取的 instance-name  logic-name 不能相同
    # 实例名
    instance-name: sc-mssql-connector
    # 逻辑名
    logic-name: sc-mssql-customer
    # 读取的表
    include-table: dbo.PfSObjDeviceBind
    # 读取的库
    include-db: GPS


spring:
  datasource:
    dynamic:
      datasource:
        mysql:
          url: jdbc:mysql://localhost:3306/data-sync-task?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&AllowPublicKeyRetrieval=True
          username: root
          password: rootroot
          driver-class-name: com.mysql.jdbc.Driver

        sqlserver:
          url: jdbc:sqlserver://localhost:1433;DatabaseName=liuhao
          username: SA
          password: Root@1234
          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

mybatis-plus:
  mapper-locations: mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  type-aliases-package: com.liuhao.datasynctask.entity


person:
  name: liuhao
  age: 100