server:
  port: 37283
logging:
  file:
    path: /Users/liuhao/Downloads/JavaProjects/DataSyncTask/logs
    name: /Users/liuhao/Downloads/JavaProjects/DataSyncTask/logs/DataSyncTask-1.logs
  level:
    root: info